name: Generate GitHub Contribution Snake

on:
  schedule:
    - cron: "0 0 * * *" # Every midnight
  workflow_dispatch:

jobs:
  generate:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: Platane/snk@v3
        with:
          github_user_name: HasinthakaPiyumal
          outputs: |
            dist/github-contribution-grid-snake.svg

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist/github-contribution-grid-snake.svg
          git commit -m "Generate contribution snake"
          git push
        env:
          GITHUB_TOKEN: ${{ secrets.PAT }}
